NutriApp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('nutri-consult/', include('nutriconsult.urls')),
]

nutriconsult/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('change-password/', auth_views.PasswordChangeView.as_view(), name='change_password'),
    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('reset-password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset-password/complete', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register-assistant/', views.assistant_register, name='assistant_register'),
    path('register-nutritionist/', views.nutritionist_register, name='nutritionist_register'),
    path('register-client/', views.client_register, name='client_register'),
    path('make-consult/', views.make_consult, name='make_consult'),
    path('patient-detail/<int:client_id>/', views.patient_details, name='patient_detail'),
    path('patient-progress/', views.patient_progress, name='patient_progress'),
]

nutriconsult/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Client(models.Model):
    first_name = models.CharField(max_length=50, blank=False, null=False)
    last_name = models.CharField(max_length=50, blank=False, null=False)
    birthday = models.DateField(blank=False, null=False)
    sex_choices = [("Male", "Male"),
                   ("Female", "Female"), ]
    sex = models.CharField(max_length=10, blank=False, null=False, choices=sex_choices)
    height = models.CharField(max_length=6, blank=False, null=False)
    weight = models.CharField(max_length=6, blank=False, null=False)
    exersice_choices = [("Yes", "yes"),
                        ("No", "no"), ]
    exersice = models.CharField(max_length=10, blank=False, null=False, choices=exersice_choices)
    nutritionist = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_active = models.BooleanField()

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Consult(models.Model):
    consult_date = models.DateField(auto_now_add=True, blank=False, null=False)
    new_weight = models.CharField(max_length=6, blank=False, null=False)
    observation = models.TextField(blank=True, null=False)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    nutritionist = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'Consult: {self.consult_date}' + ' ' + self.new_weight + ' ' + self.observation

nutriconsult/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Client, Consult


# Create forms here
class AssistantRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Retype your password", widget=forms.PasswordInput)

    class Meta:
        model = User

        fields = ['username', 'first_name', 'last_name', 'email', 'is_staff']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords don't match, please try again")
        return cd['password2']


class NutritionistRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Retype your password", widget=forms.PasswordInput)

    class Meta:
        model = User

        fields = ['username', 'first_name', 'last_name', 'email', 'is_superuser']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords don't match, please try again")
        return cd['password2']


class ClientRegistrationForm(forms.ModelForm):
    nutritionist = forms.ModelChoiceField(queryset=User.objects.filter(is_superuser=True))

    class Meta:
        model = Client

        fields = ['first_name', 'last_name', 'birthday', 'sex', 'height', 'weight', 'exersice', 'nutritionist',
                  'is_active']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nutritionist'].queryset = User.objects.filter(is_superuser=True)


class MakeConsult(forms.ModelForm):
    nutritionist = forms.ModelChoiceField(queryset=User.objects.filter(is_superuser=True))

    class Meta:
        model = Consult

        fields = ['new_weight', 'observation', 'client', 'nutritionist']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nutritionist'].queryset = User.objects.filter(is_superuser=True)

nutriconsult/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import AssistantRegistrationForm, NutritionistRegistrationForm, ClientRegistrationForm, MakeConsult
from .models import Client, Consult
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q


# Create your views here.
def dashboard(request):
    if 'patient' in request.GET:
        patient = request.GET['patient']
        all_clients = Client.objects.filter(Q(first_name__icontains=patient) | Q(last_name__icontains=patient))
    else:
        all_clients = Client.objects.filter(is_active=1).order_by('last_name')
    all_user = User.objects.all()
    paginator = Paginator(all_clients, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'nutriconsult/dashboard.html', {'all_clients': all_clients, 'all_user': all_user,
                                                           'page_obj': page_obj})


@login_required
def assistant_register(request):
    if request.method == 'POST':
        assistant_form = AssistantRegistrationForm(request.POST)
        if assistant_form.is_valid():
            new_user = assistant_form.save(commit=False)
            new_user.set_password(assistant_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'nutriconsult/register_done.html', {'new_user': new_user})
    else:
        assistant_form = AssistantRegistrationForm()
        return render(request, 'nutriconsult/register_assistant.html', {'assistant_form': assistant_form})


@login_required
def nutritionist_register(request):
    if request.method == 'POST':
        nutritionist_form = NutritionistRegistrationForm(request.POST)
        if nutritionist_form.is_valid():
            new_user = nutritionist_form.save(commit=False)
            new_user.set_password(nutritionist_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'nutriconsult/register_done.html', {'new_user': new_user})
    else:
        nutritionist_form = NutritionistRegistrationForm()
        return render(request, 'nutriconsult/register_nutritionist.html', {'nutritionist_form': nutritionist_form})


@login_required
def client_register(request):
    if request.method == 'POST':
        client_form = ClientRegistrationForm(request.POST)
        if client_form.is_valid():
            new_client = client_form.save(commit=False)
            new_client.save()
            return render(request, 'nutriconsult/register_client_done.html', {'new_client': new_client})
    else:
        client_form = ClientRegistrationForm()
        return render(request, 'nutriconsult/register_client.html', {'client_form': client_form})


@login_required
def make_consult(request):
    if request.method == 'POST':
        consult_form = MakeConsult(request.POST)
        if consult_form.is_valid():
            new_consult = consult_form.save(commit=False)
            new_consult.save()
            return render(request, 'nutriconsult/consult_done.html', {'new_consult': new_consult})
    else:
        consult_form = MakeConsult()
        return render(request, 'nutriconsult/make_consult.html', {'consult_form': consult_form})


@login_required
def patient_details(request, client_id=None):
    client = get_object_or_404(Client, pk=client_id)
    all_client = Client.objects.all()
    all_consult = Consult.objects.filter(client=client).order_by('consult_date')

    bmi = round(float(client.weight)/(float(client.height)**2), 2)

    previous_consult = all_consult.last()
    if previous_consult:
        current_bmi = round(float(previous_consult.new_weight)/(float(client.height)**2), 2)
    else:
        current_bmi = None

    return render(request, 'nutriconsult/client_detail.html', {'client': client, 'all_client': all_client,
                                                               'all_consult': all_consult, 'bmi': bmi,
                                                               'current_bmi': current_bmi})


def patient_progress(request):
    client_id = request.GET.get('client_id')
    client = get_object_or_404(Client, id=client_id)
    consult = Consult.objects.filter(client=client).order_by('consult_date')

    bmi = round(float(client.weight)/(float(client.height)**2), 2)
    previous_consult = consult.last()
    if previous_consult:
        current_bmi = round(float(previous_consult.new_weight) / (float(client.height) ** 2), 2)
    else:
        current_bmi = None

    return render(request, 'nutriconsult/patient_progress.html', {'client': client, 'consult': consult,
                                                                  'bmi': bmi, "current_bmi": current_bmi})

nutriconsult/templates/nutriconsult/client_detail.html
{% extends 'base.html' %}
{% block title %} Client Details {% endblock %}
{% block content %}

    <div class="container position-absolute top-50 start-50 translate-middle">

            <h1>Client Details</h1>

            <table class="table table-dark table-striped">
                <thead>
                    <tr>
                        <th class="text-center" scope="col">Id</th>
                        <th class="text-center" scope="col">Client</th>
                        <th class="text-center" scope="col">Birthday</th>
                        <th class="text-center" scope="col">Gender</th>
                        <th class="text-center" scope="col">Height:</th>
                        <th class="text-center" scope="col">Weight:</th>
                        <th class="text-center" scope="col">Exercise:</th>
                        <th class="text-center" scope="col">First Bmi</th>
                        <th class="text-center" scope="col">Current Bmi</th>

                    </tr>
                </thead>
                <tbody>
                        <tr>
                            <th class="text-center">{{ client.id }}</th>
                            <th class="text-center">{{ client.first_name }} {{ client.last_name }}</th>
                            <td class="text-center">{{ client.birthday }}</td>
                            <td class="text-center">{{ client.sex }}</td>
                            <td class="text-center">{{ client.height }} mts</td>
                            <td class="text-center">{{ client.weight }} kg</td>
                            <td class="text-center">{{ client.exersice }}</td>
                            <td class="text-center">{{ bmi }}</td>
                            <td class="text-center">{{ current_bmi }}</td>
                        </tr>
                </tbody>
            </table>

            <table class="table table-dark table-striped">
                <thead>
                    <tr>
                        <th class="text-center" scope="col">Consult date</th>
                        <th class="text-center" scope="col">New Weight</th>
                        <th class="text-center" scope="col">Observations</th>
                    </tr>
                </thead>
                <tbody>
                    {% for consult in all_consult  %}
                        <tr>
                            <td class="text-center">{{ consult.consult_date }}</td>
                            <td class="text-center">{{ consult.new_weight }}</td>
                            <td class="text-center">{{ consult.observation }}</td>
                        </tr>
                    {% empty %}
                    {% endfor %}
                </tbody>
            </table>

        <a class="btn btn-primary" href="{% url 'dashboard' %}" role="button">Return to Dashboard</a>
    </div>

{% endblock %}

nutriconsult/templates/nutriconsult/consult_done.html
{% extends "base.html" %}
{% block title %}Consult Confirmation{% endblock %}
{% block content %}

    <section>
        <div class="container position-absolute top-50 start-50 translate-middle">
            <div class="row">
                <div class="col-12 col-sm-8 col-md-6 m-auto">
                    <div class="card border-0 shadow">
                        <div class="card-body text-center">

                            <h1>Consult Done</h1>
                            <p>The consult has been successfully created</p>
                            <a class="btn btn-primary" href="{% url 'dashboard' %}" role="button">Return to Dashboard</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

nutriconsult/templates/nutriconsult/make_consult.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %} Make Consult {% endblock %}
{% block content %}

    <section>
        <div class="container position-absolute top-50 start-50 translate-middle">
            <div class="row">
                <div class="col-12 col-sm-8 col-md-6 m-auto">
                    <div class="card border-0 shadow">
                        <div class="card-body text-center">

                            <form method="post">

                                {% csrf_token %}

                                <h1>New Consult</h1>
                                <p>Please, fill the following form:</p>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="new_weight" maxlength="6" id="id_new_weight" placeholder="Weight" required>
                                    <label for="id_new_weight">New Weight</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <textarea class="form-control" name="observation" cols="40" rows="10" id="id_observation" placeholder="Observation"></textarea>
                                    <label for="id_observation">Observations</label>
                                </div>

                                <br>

                                {{ consult_form.client|add_class:"form-select" }}

                                <br>

                                {{ consult_form.nutritionist|add_class:"form-select" }}

                                <br>

                                <div class="col-12">
                                    <button class="btn btn-primary" type="submit">Make Consult</button>
                                </div>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

nutriconsult/templates/nutriconsult/patient_progress.html
{% extends 'base.html' %}
{% block title %} Patient Progress {% endblock %}
{% block content %}

    <section>
            <div class="container position-absolute top-50 start-50 translate-middle">
                <div class="row">
                    <div class="col-12 col-sm-8 col-md-6 m-auto">
                        <div class="card border-0 shadow">
                            <div class="card-body text-center">

                                <!--Still in develop-->
                                <h1>Progress of: {{ client.first_name }} {{ client.last_name }}</h1>
                                <p><strong>Birthday: </strong>{{ client.birthday }}</p>
                                <p><strong>Gender: </strong>{{ client.sex }}</p>
                                <p><strong>Height: </strong>{{ client.height }} mts</p>
                                <p><strong>Initial Weight: </strong>{{ client.weight }} kg</p>
                                <p><strong>Exercise: </strong>{{ client.exersice }}</p>
                                <p><strong>Initial BMI: </strong>{{ bmi }}</p>
                                <p><strong>Current BMI: </strong>{{ current_bmi }}</p>

                                <table class="table table-dark table-striped rounded-1">
                                    <thead>
                                        <tr>
                                            <th class="text-center" scope="col">Consult date</th>
                                            <th class="text-center" scope="col">New Weight</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for consult in consult  %}
                                            <tr>
                                                <td class="text-center">{{ consult.consult_date }}</td>
                                                <td class="text-center">{{ consult.new_weight }} kg</td>
                                            </tr>
                                        {% empty %}
                                        {% endfor %}
                                    </tbody>
                                </table>

                                <a class="btn btn-primary" href="{% url 'dashboard' %}" role="button">Return to Dashboard</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>


{% endblock %}

nutriconsult/templates/nutriconsult/register_assistant.html
{% extends "base.html" %}
{% block title %} Register Assistant {% endblock %}
{% block content %}

     <section>
        <div class="container position-absolute top-50 start-50 translate-middle">
            <div class="row">
                <div class="col-12 col-sm-8 col-md-6 m-auto">
                    <div class="card border-0 shadow">
                        <div class="card-body text-center">

                            <form method="post">

                                {% csrf_token %}

                                <h1>Create an Assistant Account</h1>
                                <p>Please, fill the following form:</p>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="username" id="id_username" maxlength="150" placeholder="username" required>
                                    <label for="id_username">Username</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="first_name" id="id_first_name" maxlength="150" placeholder="firstname" required>
                                    <label for="id_first_name">First Name</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="last_name" id="id_last_name" maxlength="150" placeholder="lastname" required>
                                    <label for="id_last_name">Last Name</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="email" class="form-control" name="email" id="id_email" maxlength="254" placeholder="email" required>
                                    <label for="id_email">Email</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="password" class="form-control" name="password" id="id_password" placeholder="password" required>
                                    <label for="id_password">Password</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="password" class="form-control" name="password2" id="id_password2" placeholder="password2" required>
                                    <label for="id_password2">Retype your password</label>
                                </div>

                                <br>

                                <input type="hidden" name="is_staff" id="id_is_staff" value="1">

                                <div class="col-12">
                                    <button class="btn btn-primary" type="submit">Create Assistant</button>
                                </div>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

nutriconsult/templates/nutriconsult/register_client.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %} Create Client {% endblock %}
{% block content %}

     <section>
        <div class="container position-absolute top-50 start-50 translate-middle">
            <div class="row">
                <div class="col-12 col-sm-8 col-md-6 m-auto">
                    <div class="card border-0 shadow">
                        <div class="card-body text-center">

                            <form method="post">

                                {% csrf_token %}

                                <h1>Register a Client</h1>
                                <p>Please, fill the following form:</p>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="first_name" id="id_first_name" maxlength="50" placeholder="first name" required>
                                    <label for="id_first_name">First Name</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="last_name" id="id_last_name" maxlength="50" placeholder="lastname" required>
                                    <label for="id_last_name">Last Name</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="birthday" id="id_birthday" maxlength="10" placeholder="birthday" required>
                                    <label for="id_birthday">yyyy-mm-dd</label>
                                </div>

                                <br>

                                <select class="form-select" aria-label="Default select example" name="sex" required>
                                    <option selected>Sex?</option>
                                    <option value="Male">Male</option>
                                    <option value="Female">Female</option>
                                </select>

                                <br>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="height" maxlength="6" id="id_height" placeholder="Height" required>
                                    <label for="id_height">Height</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="weight" maxlength="6" id="id_weight" placeholder="Weight" required>
                                    <label for="id_weight">Weight</label>
                                </div>

                                <br>

                                <select class="form-select" aria-label="Default select example" name="exersice" required>
                                    <option selected>Exersice?</option>
                                    <option value="Yes">Yes</option>
                                    <option value="No">No</option>
                                </select>

                                <br>

                                {{ client_form.nutritionist|add_class:"form-select" }}

                                <br>

                                <div class="form-check">
                                  <input class="form-check-input" type="checkbox" value="True" name="is_active" id="flexCheckChecked" checked>
                                  <label class="form-check-label" for="flexCheckChecked">
                                      Regular customer
                                  </label>
                                </div>
                                <div class="form-check">
                                  <input class="form-check-input" type="checkbox" value="False" name="is_active"  id="flexCheckDefault">
                                  <label class="form-check-label" for="flexCheckDefault">
                                    Once Time Customer
                                  </label>
                                </div>

                                <br>

                                <div class="col-12">
                                    <button class="btn btn-primary" type="submit">Register</button>
                                </div>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

nutriconsult/templates/nutriconsult/register_client_done.html
{% extends "base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}

    <section>
        <div class="container position-absolute top-50 start-50 translate-middle">
            <div class="row">
                <div class="col-12 col-sm-8 col-md-6 m-auto">
                    <div class="card border-0 shadow">
                        <div class="card-body text-center">

                            <h1>Welcome to the NutriFamily</h1>
                            <p>The Client has been successfully created</p>
                            <a class="btn btn-primary" href="{% url 'dashboard' %}" role="button">Return to Dashboard</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

nutriconsult/templates/nutriconsult/register_nutritionist.html
{% extends "base.html" %}
{% block title %} Register Nutritionist {% endblock %}
{% block content %}

     <section>
        <div class="container position-absolute top-50 start-50 translate-middle">
            <div class="row">
                <div class="col-12 col-sm-8 col-md-6 m-auto">
                    <div class="card border-0 shadow">
                        <div class="card-body text-center">

                            <form method="post">

                                {% csrf_token %}

                                <h1>Create a Nutritionist Account</h1>
                                <p>Please, fill the following form:</p>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="username" id="id_username" maxlength="150" placeholder="username" required>
                                    <label for="id_username">Username</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="first_name" id="id_first_name" maxlength="150" placeholder="firstname" required>
                                    <label for="id_first_name">First Name</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="text" class="form-control" name="last_name" id="id_last_name" maxlength="150" placeholder="lastname" required>
                                    <label for="id_last_name">Last Name</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="email" class="form-control" name="email" id="id_email" maxlength="254" placeholder="email" required>
                                    <label for="id_email">Email</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="password" class="form-control" name="password" id="id_password" placeholder="password" required>
                                    <label for="id_password">Password</label>
                                </div>

                                <br>

                                <div class="form-floating">
                                    <input type="password" class="form-control" name="password2" id="id_password2" placeholder="password2" required>
                                    <label for="id_password2">Retype your password</label>
                                </div>

                                <br>

                                <input type="hidden" name="is_superuser" id="id_is_superuser" value="1">

                                <div class="col-12">
                                    <button class="btn btn-primary" type="submit">Create Nutritionist</button>
                                </div>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}